# mount drive

In [1]:
# from google.colab import drive
# drive.mount('/content/drive')

# importing libraries

In [2]:
import pandas as pd
import numpy as np
import random
import kagglehub
import os
import json
import joblib
from sklearn.preprocessing import MinMaxScaler,StandardScaler
from scipy.signal import savgol_filter

c:\Users\ahmed\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\__init__.py:113: RequestsDependencyWarning: urllib3 (2.5.0) or chardet (6.0.0.post1)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn(
c:\Users\ahmed\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
SEED = 42

random.seed(SEED)
np.random.seed(SEED)

# Project Paths

In [4]:
BASE_PATH = "../Data/"
RAW_PATH = os.path.join(BASE_PATH, "raw_data")
SAVE_PATH = os.path.join(BASE_PATH, "swat_preprocessed")

os.makedirs(SAVE_PATH, exist_ok=True)
os.makedirs(RAW_PATH, exist_ok=True)

print("raw path:", RAW_PATH)
print("Save path:", SAVE_PATH)

raw path: ../Data/raw_data
Save path: ../Data/swat_preprocessed

# Configuration

In [5]:
CONFIG = {
    "train_ratio": 0.9,
    "val_ratio": 0.05,
    "test_ratio": 0.05,  

    "window_size": 12,
    "step_size": 1,

    "smoothing": False,  # ❗ safer default
    "smoothing_window": 5,

    "stabilization_hours": 1
}

# Load SWaT Data

In [6]:
attack=pd.read_csv(f"{RAW_PATH}/attack_data.csv")
normal=pd.read_csv(f"{RAW_PATH}/normal_data.csv")

In [7]:
attack.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54621 entries, 0 to 54620
Data columns (total 53 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Timestamp  54621 non-null  object
 1   FIT101     54621 non-null  float64
 2   LIT101     54621 non-null  float64
 3   MV101      54621 non-null  float64
 4   P101       54621 non-null  int64
 5   P102       54621 non-null  int64
 6   AIT201     54621 non-null  float64
 7   AIT202     54621 non-null  float64
 8   AIT203     54621 non-null  float64
 9   FIT201     54621 non-null  float64
 10  MV201      54621 non-null  float64
 11  P201       54621 non-null  float64
 12  P202       54621 non-null  float64
 13  P203       54621 non-null  int64
 14  P204       54621 non-null  float64
 15  P205       54621 non-null  int64
 16  P206       54621 non-null  int64
 17  DPIT301    54621 non-null  float64
 18  FIT301     54621 non-null  float64
 19  LIT301     54621 non-null  float64
 20  MV301      54621 non-null  int64
 21  MV302      54621 non-null  int64
 22  MV303      54621 non-null  float64
 23  MV304      54621 non-null  int64
 24  P301       54621 non-null  int64
 25  P302       54621 non-null  int64
 26  AIT401     54621 non-null  float64
 27  AIT402     54621 non-null  float64
 28  FIT401     54621 non-null  float64
 29  LIT401     54621 non-null  float64
 30  P401       54621 non-null  int64
 31  P402       54621 non-null  int64
 32  P403       54621 non-null  int64
 33  P404       54621 non-null  int64
 34  UV401      54621 non-null  int64
 35  AIT501     54621 non-null  float64
 36  AIT502     54621 non-null  float64
 37  AIT503     54621 non-null  float64
 38  AIT504     54621 non-null  float64
 39  FIT501     54621 non-null  float64
 40  FIT502     54621 non-null  float64
 41  FIT503     54621 non-null  float64
 42  FIT504     54621 non-null  float64
 43  P501       54621 non-null  int64
 44  P502       54621 non-null  int64
 45  PIT501     54621 non-null  float64
 46  PIT502     54621 non-null  float64
 47  PIT503     54621 non-null  float64
 48  FIT601     54621 non-null  float64
 49  P601       54621 non-null  int64
 50  P602       54621 non-null  int64
 51  P603       54621 non-null  int64
 52  label      54621 non-null  int64
dtypes: float64(31), int64(21), object(1)
memory usage: 22.1+ MB

In [8]:
df=pd.read_csv(f"{RAW_PATH}/merged_data.csv")

In [9]:
print("Attack data shape:", attack.shape)
print("Normal data shape:", normal.shape)

Attack data shape: (54621, 53)
Normal data shape: (1387098, 53)

# cleaning data

## make date as index

In [10]:
def fix_time_index(df):
    df["Timestamp"] = pd.to_datetime(df["Timestamp"])
    df = df.set_index("Timestamp")
    # Sort
    df = df.sort_index()
    return df

## Remove Stabilization Period

In [11]:
def remove_stabilization(df, hours):
    return df.iloc[int(hours * 3600):]

## Remove Constant Features

In [12]:
def drop_common_constant_columns(df1, df2, label_col="label"):
    const_df1 = set(c for c in df1.columns
                    if df1[c].nunique() <= 1 and c != label_col)
    const_df2 = set(c for c in df2.columns
                    if df2[c].nunique() <= 1 and c != label_col)

    common_constant_cols = list(const_df1.intersection(const_df2))

    df1 = df1.drop(columns=common_constant_cols)
    df2 = df2.drop(columns=common_constant_cols)

    return df1, df2, common_constant_cols

normal, attack, dropped_cols = drop_common_constant_columns(normal, attack)

print("Dropped constant columns:", dropped_cols)

Dropped constant columns: ['P401', 'P502', 'P601', 'P404', 'P603']

## Fix Timestamp Gaps

In [13]:
def fix_time_gaps(df, method="interpolate"):
    if method == "ffill":
        return df.ffill()
    elif method == "interpolate":
        return df.interpolate()
    else:
        raise ValueError("Unknown method")

In [14]:
normal.shape

(1387098, 48)

In [15]:
print("Duplicate timestamps (normal):", normal["Timestamp"].duplicated().sum())
print("Duplicate timestamps (attack):", attack["Timestamp"].duplicated().sum())

Duplicate timestamps (normal): 495000
Duplicate timestamps (attack): 0

In [16]:
print("Columns:", normal.columns)

if "Timestamp" in normal.columns:
    print("Duplicate timestamps (normal):", normal["Timestamp"].duplicated().sum())
else:
    print("Duplicate index (normal):", normal.index.duplicated().sum())

Columns: Index(['Timestamp', 'FIT101', 'LIT101', 'MV101', 'P101', 'P102', 'AIT201',
       'AIT202', 'AIT203', 'FIT201', 'MV201', 'P201', 'P202', 'P203', 'P204',
       'P205', 'P206', 'DPIT301', 'FIT301', 'LIT301', 'MV301', 'MV302',
       'MV303', 'MV304', 'P301', 'P302', 'AIT401', 'AIT402', 'FIT401',
       'LIT401', 'P402', 'P403', 'UV401', 'AIT501', 'AIT502', 'AIT503',
       'AIT504', 'FIT501', 'FIT502', 'FIT503', 'FIT504', 'P501', 'PIT501',
       'PIT502', 'PIT503', 'FIT601', 'P602', 'label'],
      dtype='object')
Duplicate timestamps (normal): 495000

In [17]:
# Fix time index
normal = fix_time_index(normal)
attack = fix_time_index(attack)

In [18]:


# Remove stabilization
normal = remove_stabilization(normal, CONFIG["stabilization_hours"])
attack = remove_stabilization(attack, CONFIG["stabilization_hours"])

# Fix gaps
normal = fix_time_gaps(normal, method="interpolate")
attack = fix_time_gaps(attack, method="interpolate")

In [19]:
normal.shape

(1383498, 47)

In [20]:
normal

,FIT101,LIT101,MV101,P101,P102,AIT201,AIT202,AIT203,FIT201,MV201,...,FIT502,FIT503,FIT504,P501,PIT501,PIT502,PIT503,FIT601,P602,label
Timestamp,,,,,,,,,,,,,,,,,,,,,
2015-12-22 16:45:00,2.661179,253.5728,0.0,2,1,0.0000,8.358626,332.5045,2.475379,0.0,...,0.001409,0.001664,0.000000,1,10.38195,0.000000,4.614202,0.000128,1,0
2015-12-22 16:45:00,2.661179,253.5728,0.0,2,1,0.0000,8.358626,332.5045,2.475379,0.0,...,0.001409,0.001664,0.000000,1,10.38195,0.000000,4.614202,0.000128,1,0
2015-12-22 16:45:01,2.661179,253.8476,0.0,2,1,0.0000,8.358626,333.2223,2.475379,0.0,...,0.001409,0.001664,0.000000,1,10.38195,0.000000,4.614202,0.000128,1,0
2015-12-22 16:45:01,2.661179,253.8476,0.0,2,1,0.0000,8.358626,333.2223,2.475379,0.0,...,0.001409,0.001664,0.000000,1,10.38195,0.000000,4.614202,0.000128,1,0
2015-12-22 16:45:02,2.642923,254.0439,0.0,2,1,0.0000,8.358626,333.9144,2.475379,0.0,...,0.001409,0.001664,0.000000,1,10.38195,0.000000,4.614202,0.000128,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-01-02 14:59:55,2.559972,519.5495,2.0,2,1,168.0979,8.638683,301.9226,2.459488,2.0,...,1.288971,0.734885,0.306569,2,251.15350,0.865024,189.022000,0.000000,1,0
2016-01-02 14:59:56,2.549082,520.4131,2.0,2,1,168.0979,8.638683,301.9226,2.459488,2.0,...,1.272704,0.734885,0.306569,2,251.07340,0.865024,188.925900,0.000000,1,0
2016-01-02 14:59:57,2.531467,520.6878,2.0,2,1,168.0979,8.638683,301.9226,2.460129,2.0,...,1.269502,0.734885,0.306569,2,251.07340,0.865024,188.925900,0.000000,1,0
2016-01-02 14:59:58,2.521218,520.7271,2.0,2,1,168.0979,8.638683,301.9226,2.460129,2.0,...,1.263866,0.734885,0.307978,2,251.07340,0.865024,188.925900,0.000000,1,0
2016-01-02 14:59:59,2.501681,521.1196,2.0,2,1,168.0979,8.638683,301.9226,2.458206,2.0,...,1.272704,0.734885,0.308298,2,251.07340,0.865024,188.925900,0.000000,1,0

In [21]:
attack

,FIT101,LIT101,MV101,P101,P102,AIT201,AIT202,AIT203,FIT201,MV201,...,FIT502,FIT503,FIT504,P501,PIT501,PIT502,PIT503,FIT601,P602,label
Timestamp,,,,,,,,,,,,,,,,,,,,,
2015-12-28 13:23:49,2.638760,660.9379,2.0,1,1,263.6183,8.418867,318.7644,0.000000,1.0,...,1.312028,0.733220,0.309067,2,246.5554,1.649953,185.8498,1.709736,2,1
2015-12-28 13:23:50,2.624988,661.4090,2.0,1,1,263.6183,8.418867,318.7644,0.000000,1.0,...,1.304855,0.732580,0.307786,2,246.5554,1.649953,186.0901,1.720693,2,1
2015-12-28 13:23:51,2.620504,661.0164,2.0,1,1,263.6183,8.418867,318.7644,0.000000,1.0,...,1.291789,0.732580,0.307786,2,246.7316,1.649953,186.2023,1.730112,1,1
2015-12-28 13:23:52,2.619223,661.3697,2.0,1,1,263.6183,8.418867,318.7644,0.000000,1.0,...,1.291789,0.732580,0.308298,2,246.8117,1.649953,186.2023,1.730625,1,1
2015-12-28 13:23:53,2.602569,661.9193,2.0,1,1,263.6183,8.415342,318.7644,0.000000,1.0,...,1.282439,0.732580,0.308426,2,246.9559,1.649953,186.2023,1.729600,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-01-02 13:41:07,2.534670,524.1028,2.0,2,1,168.8990,8.633236,304.5373,2.461026,2.0,...,1.255284,0.734629,0.306569,2,249.5193,0.945119,187.5801,0.000000,1,1
2016-01-02 13:41:08,2.517055,524.2206,2.0,2,1,168.8990,8.633236,304.5373,2.461026,2.0,...,1.246189,0.734629,0.308362,2,249.5193,0.945119,187.5801,0.000000,1,1
2016-01-02 13:41:09,2.502322,524.2206,2.0,2,1,168.8990,8.633236,304.5373,2.461026,2.0,...,1.244396,0.734629,0.308042,2,249.5193,0.945119,187.5801,0.000000,1,1
2016-01-02 13:41:10,2.482465,524.2991,2.0,2,1,168.8990,8.634518,304.5373,2.461026,2.0,...,1.265659,0.734629,0.306633,2,249.5193,0.945119,187.5801,0.000000,1,1
2016-01-02 13:41:11,2.469654,524.2206,2.0,2,1,168.8990,8.635479,304.5373,2.461026,2.0,...,1.285001,0.734629,0.306633,2,249.5193,0.945119,187.5801,0.000000,1,1

# feature engineering

## Identify Sensor Columns

In [22]:
feature_cols = [c for c in normal.columns if c != "label"]

## Smooth Sensors (Rolling Average)

In [23]:
# ============================================================
# Optional signal smoothing
# ============================================================

def smooth_signals(df, feature_cols, window=5, enable=True):

    if not enable:
        print("Skipping smoothing.")
        return df

    df = df.copy()

    df[feature_cols] = (
        df[feature_cols]
        .rolling(window=window, min_periods=1)
        .mean()
    )

    print(f"Smoothing applied with window={window}")

    return df

In [24]:

normal = smooth_signals(normal, feature_cols, CONFIG["smoothing_window"], CONFIG['smoothing'])
attack = smooth_signals(attack, feature_cols, CONFIG["smoothing_window"], CONFIG['smoothing'])

Skipping smoothing.
Skipping smoothing.

## Proper Train / Validation Split

In [25]:
n = len(normal)

train_end = int(n * CONFIG["train_ratio"])
val_end = int(n * (CONFIG["train_ratio"] + CONFIG["val_ratio"]))

normal_train = normal.iloc[:train_end]
normal_val = normal.iloc[train_end:val_end]
normal_test = normal.iloc[val_end:]

In [26]:
test_data = pd.concat([normal_test, attack])

In [27]:
attack.isna().sum()

FIT101     0
LIT101     0
MV101      0
P101       0
P102       0
AIT201     0
AIT202     0
AIT203     0
FIT201     0
MV201      0
P201       0
P202       0
P203       0
P204       0
P205       0
P206       0
DPIT301    0
FIT301     0
LIT301     0
MV301      0
MV302      0
MV303      0
MV304      0
P301       0
P302       0
AIT401     0
AIT402     0
FIT401     0
LIT401     0
P402       0
P403       0
UV401      0
AIT501     0
AIT502     0
AIT503     0
AIT504     0
FIT501     0
FIT502     0
FIT503     0
FIT504     0
P501       0
PIT501     0
PIT502     0
PIT503     0
FIT601     0
P602       0
label      0
dtype: int64

## Apply Scaling

In [28]:
scaler = MinMaxScaler()

# Fit ONLY on train
scaler.fit(normal_train)

# Transform everything
normal_train = scaler.transform(normal_train)
normal_val = scaler.transform(normal_val)
normal_test = scaler.transform(normal_test)
attack_scaled = scaler.transform(attack)

In [29]:
joblib.dump(scaler, os.path.join(SAVE_PATH, "scaler.pkl"))

['../Data/swat_preprocessed\\scaler.pkl']

## Window Function

In [30]:
def create_windows(data, labels=None, window_size=CONFIG['window_size'], step=1):
    X, y = [], []

    for i in range(0, len(data) - window_size, step):
        X.append(data[i:i+window_size])

        if labels is not None:
            # ✅ NO FUTURE LEAKAGE
            y.append(max(labels[i:i+window_size]))

    return np.array(X), np.array(y) if labels is not None else None

In [31]:
attack_labels = attack["label"].values
normal_labels = np.zeros(len(normal))

In [32]:
test_labels = np.concatenate([
    np.zeros(len(normal_test)),
    attack_labels
])

## Create Windows

In [33]:
X_train, _ = create_windows(normal_train, window_size=CONFIG["window_size"])
X_val, _ = create_windows(normal_val, window_size=CONFIG["window_size"])

X_test, y_test = create_windows(
    np.vstack([normal_test, attack_scaled]),
    labels=test_labels,
    window_size=CONFIG["window_size"]
)

In [34]:
# ============================================================
# Dataset summary
# ============================================================

print("X_train:", X_train.shape)
print("X_val:", X_val.shape)
print("X_test:", X_test.shape)

print("y_test:", y_test.shape)
print("Anomaly ratio in test:", y_test.mean())

X_train: (1245136, 12, 47)
X_val: (69163, 12, 47)
X_test: (120184, 12, 47)
y_test: (120184,)
Anomaly ratio in test: 0.4245157425281235

In [35]:
nan_per_feature = np.isnan(X_test).sum(axis=(0,1))
print(nan_per_feature)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0]

## Save Everything to Drive

In [36]:
np.save(os.path.join(SAVE_PATH, "X_train.npy"), X_train)

In [37]:
np.save(os.path.join(SAVE_PATH, "X_val.npy"), X_val)

In [38]:
np.save(os.path.join(SAVE_PATH, "X_test.npy"), X_test)

In [39]:
np.save(os.path.join(SAVE_PATH, "y_test.npy"), y_test)

In [40]:
joblib.dump(scaler, os.path.join(SAVE_PATH, "scaler.pkl"))

with open(os.path.join(SAVE_PATH, "config.json"), "w") as f:
    json.dump(CONFIG, f, indent=2)

print("All files saved to:", SAVE_PATH)

All files saved to: ../Data/swat_preprocessed

In [41]:
with open(os.path.join(SAVE_PATH, "feature_columns.json"), "w") as f:
    json.dump(feature_cols, f, indent=2)

print(f"Saved {len(feature_cols)} feature names to {os.path.join(SAVE_PATH, 'feature_columns.json')}.")

Saved 46 feature names to ../Data/swat_preprocessed\feature_columns.json.